---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# fars

# COURSERA: BUILDING R PACKAGES PEER GRADED ASSESSMENT
Philip Gregory   

## Create an Example Package in R 

Package: fars
GitHub:  https://github.com/Gregorypi/fars

## Data Source

The functions will be using data from the US National Highway Traffic Safety 
Administration's [Fatality Analysis Reporting 
System](https://www.nhtsa.gov/research-data/fatality-analysis-reporting-system-fars),
FARS is a nationwide census providing NHTSA, Congress and the American public yearly data regarding fatal injuries suffered in motor vehicle traffic crashes.

## Review Criteria

For this assignment you'll submit a link to the [GitHub repository](https://github.com/Gregorypi/fars) which contains
your package. This assessment will ask reviewers the following questions:

* Does this package contain the correct [R file(s) under the R/ directory](https://github.com/Gregorypi/fars/tree/master/R)?   
* Does this package contain a 
[man/](https://github.com/Gregorypi/fars/tree/master/man) with directory
corresponding documentation files?
* Does this package contain a 
[vignette](https://github.com/Gregorypi/fars/blob/master/vignettes/fars.Rmd) 
which provides a meaningful description of the package and how it should be 
used?
* Does this package have at least one test included in the [tests/](https://github.com/Gregorypi/fars/tree/master/tests/testthat) directory?
* Does this package have a [NAMESPACE](https://github.com/Gregorypi/fars/blob/master/NAMESPACE) file?
* Does the README.md file for this directory have a [Travis badge](https://travis-ci.org/Gregorypi/fars)?
* Is the build of this package passing on [Travis badge](https://travis-ci.org/Gregorypi/fars)?
* Are the build logs for this package on [Travis badge](https://travis-ci.org/Gregorypi/fars) free of any errors, warnings, or notes?


